### ISSUE TITLE
Real private mode

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket-gist-plugin#19]
Private gists are accesible if URL is known as same as GitHub Gist. However **the real private mode** might be useful in some cases .

**Comment by aadrian** [comment]
+1

**Comment by takezoe** [comment]
In gitbucket-gist-plugin 4.2.0, you can choose **Public**, **Secret** and **Private** as accessibility of your Gist.

- **Secret** is same as current private mode
- **Private** is real private mode

gitbucket-gist-plugin 4.2.0 is released with GitBucket 4.2 at the end of this month.

**Comment by aadrian** [comment]
Thank you. This looks good.

**Comment by nbkhope** [comment]
I'm sorry, but I do not understand the difference between Secret and Private. Could you elaborate?

**Comment by takezoe** [comment]
- Secret mode: The snippet isn't displayed in the snippet list, but everyone can access to it if they know URL. This mode is same as GitHub Gist's secret mode.
- Private mode: Protect the snippet physically. Only author and administrators can access to the snippet.
