### ISSUE TITLE
gist doesn't work since gitbucket 4.2.1

### ISSUE THREAD

**Issue by pgollor** [gitbucket/gitbucket-gist-plugin#32]
I had a workin gitbucket 4.1 version with a working gist plugin.
A few days ago i updated git from 4.1 directly to 4.2.1 and updated the gist plugin too.
After that, the gist plugin didn't worked with this failure:
```
org.h2.jdbc.JdbcSQLException: Feld "X3.MODE" nicht gefunden
Column "X3.MODE" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._15 AS
SELECT
    X3.UPDATED_DATE AS UPDATED_DATE,
    X3.DESCRIPTION AS DESCRIPTION,
    X3.ORIGIN_REPOSITORY_NAME AS ORIGIN_REPOSITORY_NAME,
    X3.ORIGIN_USER_NAME AS ORIGIN_USER_NAME,
    X3.MODE AS MODE,
    X3.TITLE AS TITLE,
    X3.REPOSITORY_NAME AS REPOSITORY_NAME,
    X3.USER_NAME AS USER_NAME,
    X3.REGISTERED_DATE AS REGISTERED_DATE
FROM PUBLIC.GIST X3
WHERE X3.MODE = ?1
ORDER BY =X3.REGISTERED_DATE DESC
```

Today i tried it with gitbucket 4.3 and gist plugin 4.3 but there is the same issue.
This issue is on two gitbucket installations on different servers.

Best regards
Kalle

**Comment by takezoe** [comment]
See note in the Installation section of README:
https://github.com/gitbucket/gitbucket-gist-plugin#installation

**Comment by pgollor** [comment]
Thanks. I read this note, but there was no table ```VERSIONS```.
The solution was: My database location is different from [here](https://github.com/gitbucket/gitbucket/wiki/Connect-to-H2-database).
