### ISSUE TITLE
gist plugin stopped working after gitbucket 4.2.1

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket-gist-plugin#33]
The gist plugin v 4.0.0 worked with gitbucket 4.2.1 for me, in the sense that:
- I would see a "Snippets" link on the header
- Clicking the Snippets link, or viewing `$URL/gist` would take me to a list of my snippets

See screencap from gitbucket 4.2.1
![cap1](https://cloud.githubusercontent.com/assets/3464572/19011890/29796110-8772-11e6-836e-307f87566ec8.png)

If I upgrade either gist plugin to a newer version (4.2 or 4.3); or, if I upgrade gitbucket to a new version (4.3 onward), the Snippets link is gone and manually hitting `$URL/gist` produces a "Not Found" page. See screepcap from gitbucket 4.5
![cap2](https://cloud.githubusercontent.com/assets/3464572/19011898/96dfbce0-8772-11e6-9d70-1720320e0629.png)

I do not see errors in my syslog. The Snippets simply are not there. Any idea what has happened?

**Comment by axb21** [comment]
In case it's helpful, I tried exporting data from gitbucket 4.5, and it correctly exports data about my gists. They are also located under `$HOME/.gitbucket/gist/$USER`, as they always have been. It seems something went awry with the communication between gitbucket and the plugin?

**Comment by axb21** [comment]
Anyone have thoughts on this?

**Comment by axb21** [comment]
@takezoe if it is helpful, I have two gitbucket installs, and both of them have this issue. The second one I do not upgrade often and gitbucket-core is 4.2.1 on that one. Yet the gist plugin is also 3.12 when I query the versions tables. I run both gitbucket installs in standalone mode, and have upgraded both in the following way:

- shutdown gitbucket
- download new war file
- download new gist (and other) plugin file(s)
- remove old plugin files
- place new plugin files in `$HOME/.gitbucket/plugins`
- start up gitbucket with the new war (basically `java -jar` it)

**Comment by takezoe** [comment]
@axb21 It seems to had failed to migrate from 3.12. Recent versions of GitBucket checks the database version and the plugin version strictly.

Could you attach a screenshot of schema of H2 console which shows schema of `GIST` table? I would be able to show how to repair your tables by looking that.

**Comment by axb21** [comment]
@takezoe ok, here is the `GIST` table schema from H2:

<table cellspacing="0" cellpadding="0"><tbody><tr><th>FIELD<span class="sortArrow">&nbsp;&nbsp;</span></th><th>TYPE<span class="sortArrow">&nbsp;&nbsp;</span></th><th>NULL<span class="sortArrow">&nbsp;&nbsp;</span></th><th>KEY<span class="sortArrow">&nbsp;&nbsp;</span></th><th>DEFAULT<span class="sortArrow">&nbsp;&nbsp;</span></th></tr><tr><td>USER_NAME</td><td>VARCHAR(100)</td><td>NO</td><td>PRI</td><td>NULL</td></tr><tr><td>REPOSITORY_NAME</td><td>VARCHAR(100)</td><td>NO</td><td>PRI</td><td>NULL</td></tr><tr><td>PRIVATE</td><td>BOOLEAN(1)</td><td>NO</td><td></td><td>NULL</td></tr><tr><td>TITLE</td><td>VARCHAR(100)</td><td>NO</td><td></td><td>NULL</td></tr><tr><td>DESCRIPTION</td><td>CLOB(2147483647)</td><td>YES</td><td></td><td>NULL</td></tr><tr><td>REGISTERED_DATE</td><td>TIMESTAMP(23)</td><td>NO</td><td></td><td>NULL</td></tr><tr><td>UPDATED_DATE</td><td>TIMESTAMP(23)</td><td>NO</td><td></td><td>NULL</td></tr><tr><td>ORIGIN_USER_NAME</td><td>VARCHAR(100)</td><td>YES</td><td></td><td>NULL</td></tr><tr><td>ORIGIN_REPOSITORY_NAME</td><td>VARCHAR(100)</td><td>YES</td><td></td><td>NULL</td></tr></tbody></table>

**Comment by takezoe** [comment]
@axb21 OK. Execute following SQL and restart GitBucket.
```sql
UPDATE VERSIONS SET VERSION='2.0.0' WHERE MODULE_ID='gist';
```
Gist plugin will be migrated to 4.2.1 and it should work.

**Comment by axb21** [comment]
That appears to have worked on both my instances. The Snippets link is back, and when I click it I see my snippets and can interact with them as usual.

Thank you!
