### ISSUE TITLE
Empty URL markdown link causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by marklacroix** [gitbucket/gitbucket-gist-plugin#38]
| | |
| --- | --- |
| Gitbucket version | 4.8 |
| Gitbucket Gist plugin version | 4.4 |
| OS | Windows, Linux |

When a link with an empty URL is specified in markdown (e.g. `[empty link]()`), the snippet summary page (`/gist`) and user snippet summary page (`/gist/user`) fails to render with a java.lang.NullPointerException stack trace. Viewing the snippet directly does not encounter this issue.

It appears to be an issue with gitbucket core (the [fixUrl](https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/view/Markdown.scala#L149) method), but I am unable to replicate it in the core features of gitbucket.

Please let me know if I should open this as an issue on the main gitbucket project.

**Comment by takezoe** [comment]
Sorry for very delayed reaction. This is a bug of Markdown rendering in the side of GitBucket core. It's going to be fixed in https://github.com/gitbucket/gitbucket/pull/2189.
