### ISSUE TITLE
Plugin 4.5.0 listed as 4.4.0 

### ISSUE THREAD

**Issue by pozgo** [gitbucket/gitbucket-gist-plugin#39]
Even though`jar` file is 4.5.0 under plugins section still listed as 4.4.0 

ls of plugins directory . 

```
ll
total 57592
drwxr-xr-x   9 przemek  staff   306B  9 Feb 21:51 .
drwxr-xr-x@ 10 przemek  staff   340B  9 Feb 21:52 ..
-rw-r--r--   1 przemek  staff   197K  3 Feb 16:31 gitbucket-gist-plugin_2.11-4.5.0.jar
```

Screenshot of web ui. 

<img width="1111" alt="screen shot 2017-02-09 at 21 53 53" src="https://cloud.githubusercontent.com/assets/1773188/22804851/d4d8d420-ef12-11e6-96a9-769dbd6128c8.png">

**Comment by milligramme** [comment]
https://github.com/gitbucket/gitbucket-gist-plugin/commit/f5e0799507c1e4789372f4c743f8d979ed17c6d4#diff-1d282b32ffabceae75feac8a91d12adc

This issue will be solved in the next version.
