### ISSUE TITLE
Snippets Link should not be displayed if no public Gists exist!

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket-gist-plugin#41]
Snippets Link should not be displayed in header if no public Gists exist and the user is not logged in!

**Comment by nbkhope** [comment]
If you don't have the link, then how are you going to be able to create one?

**Comment by takezoe** [comment]
A user who isn't logged in can find "New snippet" button there even if no visible snippets. This button shows the logged in form for a unlogged in user, but it can be conitinue to create a new snippet after logged in.
