### ISSUE TITLE
Code blocks in markdown in "Discover Snippets" view

### ISSUE THREAD

**Issue by kmasuyama** [gitbucket/gitbucket-gist-plugin#54]
It seems the "Discover Snippets" page (from the "snippets" link at page top) and lists of single users' snippets only renders the first 10 or so lines of markdown. When a code block happens to start before line 10 and does not end by line 10, it is rendered as raw. This has the bonus of rendering any code comments made with `#` (ie bash, python) as markdown headings, resulting in large and messy previews.

I think a solution could be to ignore md code blocks if they don't get closed before line 11. A better solution would be to replace line 10 with closing ticks "```" so that the code block gets partially rendered for the preview.

This was on GitBucket 4.29.0 + gist plugin 4.16.0, running on Apache Tomcat 9

**Comment by takezoe** [comment]
That's right. However GitBucket can support any formats other than Markdown by plugins. So I think fixing Markdown isn't enough to fix this problem.

One possible solution is that it doesn't render snippet fragments as HTML at the "Discover Snippets" and the list of single user's snippets. Or restrict rendering to only Markdown might be an another solution.
